<a href="https://colab.research.google.com/github/jeffreygalle/MAT422/blob/main/Homework1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.3.1. QR decomposition

QR decomposition: breaks down a matrix A into two matrices, an orthogonal matrix Q; and an upper triangular matrix R.

If A is an m x n matrix (where m ≥ n): A = QR
where:

*   Q us an m x n matrix with orthonormal columns (i.e. Q^t*Q = I)
*   R is an n x n upper triangular matrix



## Gram-Schmidt algorithm to QR Decomposition


1.   Given a set of linear indepdent vectors {a1, a2, ..., an}, these form the **columns of matrix A**.
2.   Orthogonalization: With Gram-Schmidt we can transform the set {a1, a2, ..., an} into an orthonormal basis {q1, q2, ..., qn}.
*   Normalize: Set q1 = a1/||a1||
*   Iterate: For each ai, subtract its projection onto each of the already computed q vectors. This makes it orthogonal. Then normalize those orthogonal values to obtain the next q.
*   Build R: R is made from the coefficents from the projections (the dot product of q, i)
Together these form the **columns of the Q matrix**.
3. Building R: The coefficents that represent each ai as a combination of the orthonormal vectors q are the **upper triangular matrix R**.


   Example

---


Consider the matrix \( A \) given by:
Given the matrix A:

A = \begin{bmatrix} 1 & 2 \\ 2 & 3 \end{bmatrix}


Decompose this matrix into orthogonal (Q) and upper triangular (R) matrices so that: A = QR

Let a1 = \begin{bmatrix} 1 \\ 2 \end{bmatrix}  and a2 = \begin{bmatrix} 2 \\ 3 \end{bmatrix} \

Normalize a1 to get q1: q1 = a1/||a1|| = \begin{bmatrix} 1/sqrt(5) \\ 2/sqrt(5) \end{bmatrix}
Project a2 onto q1 and subtract:
proj_q1(a2) = (q1 * a2) * q1
Normalize u2 to get q2: q2 = u2/||u2||

The matrix R is formed using the dot product:
R = \begin{bmatrix} \mathbf{q}_1 \cdot \mathbf{a}_1 & \mathbf{q}_1 \cdot \mathbf{a}_2 \\ 0 & \mathbf{q}_2 \cdot \mathbf{a}_2 \end{bmatrix}


In [ ]:
import numpy as np

# Matrix A same as above
A = np.array([[1, 2],
              [2, 3]])

# Perform QR decomposition
Q, R = np.linalg.qr(A)

print("Matrix A:")
print(A)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)

print("\ Matrix QR:")
print(np.dot(Q, R))


Matrix A:
[[1 2]
 [2 3]]

Matrix Q:
[[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]

Matrix R:
[[-2.23606798 -3.57770876]
 [ 0.         -0.4472136 ]]
\ Matrix QR:
[[1. 2.]
 [2. 3.]]


# 1.3.2. Least-squares Problems


Least-squares Problem Defintion: Method to find the best-fitting solution to an over-determined system (more equations than unknowns (n > m).)


Goal: minimize the sum of the squares of the residuals, which are the differences between the observed values and the values predicted by the model.

Goal part-2: minimize the objective function ||Ax - b||^2, where ||.|| denotes the Euclidean norm. The solution to this minimization problem is given by the equation AᵀAx = Aᵀb, assuming A has linearly independent columns. The matrix AᵀA is guaranteed to be invertible, and the solution can be found as:
x = (AᵀA)⁻¹Aᵀb.

#1.3.3. Linear regression

In linear regression the goal is to find an affine function (short summary: takes an input, multiplies it by a constant, adds another constant to it, and produces an output) that best fits a given set of input data points {(xi, yi)}. The input data points consist of a set of xi values, where each xi is a d-dimensional vector (xi1, ..., xid)T, and their corresponding yi values. The affine function has the form f(xi) = β0 + β1xi1 + ... + βd xid, where β0, β1, ..., βd are the coefficients of the function.

How: use Least Squares. Least squares minimizes the sum of the squared differences between the predicted values and the actual values of the yi. The coefficients β0, β1, ..., βd are estimated to minimize this sum of squared differences, giving us the best-fitting affine function.

Once the coefficients are found, use the linear regression model to make predictions for new input data points